NVCC ?= nvcc
A ?= sm_80

COMMON_FLAGS = -O3 -std=c++17 -lineinfo

.RECIPEPREFIX := >

.PHONY: lib clean-lib

lib:
>mkdir -p build
>$(NVCC) $(COMMON_FLAGS) -arch=$(A) -Xcompiler -fPIC -shared src/llm_cuda_lib.cu -o build/libllm_cuda.so

clean-lib:
>rm -rf build
