NVCC ?= nvcc
A ?= sm_80

COMMON_FLAGS = -O3 -std=c++17 -lineinfo

.RECIPEPREFIX := >

.PHONY: lib deepseek-v4-a800 clean-lib

lib:
>mkdir -p build
>$(NVCC) $(COMMON_FLAGS) -arch=$(A) -Xcompiler -fPIC -shared src/llm_cuda_lib.cu -o build/libllm_cuda.so

deepseek-v4-a800:
>mkdir -p build
>$(NVCC) $(COMMON_FLAGS) -arch=$(A) -Xcompiler -fPIC -shared src/deepseek_v4_a800_kernels.cu -o build/libdeepseek_v4_a800.so

clean-lib:
>rm -rf build
